name: flutter_dex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  dynamic_color: ^1.8.1
  url_launcher: ^6.3.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  flutter_svg: ^2.2.1
  material_loading_indicator: ^1.0.0
  expressive_refresh: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/ic_pokemon.svg

  fonts:
  - family: circularstd
    fonts:
      - asset: assets/fonts/CircularStd-Book.ttf
        weight: 400
      - asset: assets/fonts/CircularStd-Medium.ttf
        weight: 500
      - asset: assets/fonts/CircularStd-Bold.ttf
        weight: 700
      - asset: assets/fonts/CircularStd-Black.ttf
        weight: 900